// Mock member data for demo purposes
import { Member } from "../../types";

export const mockMembers: Member[] = [
  {
    id: "mem_001",
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@example.com",
    phone: "123-456-7890",
    photoUrl: "/images/avatars/john-smith.jpg",
    status: "active",
    joinDate: new Date("2022-03-15"),
    lastAttendance: new Date("2025-04-06"), // Last Sunday
    homeAddress: "123 Main St, Anytown, CA 94321",
    birthDate: new Date("1985-06-12"),
    familyId: "fam_001",
    primaryBranchId: "branch_001",
    hasCard: true,
    cardId: "card_001",
    attendanceStreak: 4,
    attendanceRate: 92,
    isChild: false,
    tags: ["volunteer", "greeter", "regular"],
  },
  {
    id: "mem_002",
    firstName: "Mary",
    lastName: "Smith",
    email: "mary.smith@example.com",
    phone: "123-456-7891",
    photoUrl: "/images/avatars/mary-smith.jpg",
    status: "active",
    joinDate: new Date("2022-03-15"),
    lastAttendance: new Date("2025-04-06"), // Last Sunday
    homeAddress: "123 Main St, Anytown, CA 94321",
    birthDate: new Date("1988-09-23"),
    familyId: "fam_001",
    primaryBranchId: "branch_001",
    hasCard: true,
    cardId: "card_002",
    attendanceStreak: 4,
    attendanceRate: 85,
    isChild: false,
    tags: ["volunteer", "choir", "regular"],
  },
  {
    id: "mem_003",
    firstName: "Emma",
    lastName: "Smith",
    photoUrl: "/images/avatars/emma-smith.jpg",
    status: "active",
    joinDate: new Date("2022-03-15"),
    lastAttendance: new Date("2025-04-06"), // Last Sunday
    homeAddress: "123 Main St, Anytown, CA 94321",
    birthDate: new Date("2015-04-10"),
    familyId: "fam_001",
    primaryBranchId: "branch_001",
    hasCard: false,
    attendanceStreak: 4,
    attendanceRate: 90,
    isChild: true,
    childPickupPeople: ["mem_001", "mem_002"],
    tags: ["sunday-school", "choir"],
  },
  {
    id: "mem_004",
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    phone: "123-456-7892",
    photoUrl: "/images/avatars/michael-johnson.jpg",
    status: "active",
    joinDate: new Date("2023-01-10"),
    lastAttendance: new Date("2025-04-06"), // Last Sunday
    homeAddress: "456 Oak Ave, Anytown, CA 94321",
    birthDate: new Date("1975-11-30"),
    familyId: "fam_002",
    primaryBranchId: "branch_001",
    hasCard: true,
    cardId: "card_003",
    attendanceStreak: 2,
    attendanceRate: 75,
    isChild: false,
    tags: ["deacon", "finance-committee"],
  },
  {
    id: "mem_005",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@example.com",
    phone: "123-456-7893",
    photoUrl: "/images/avatars/sarah-johnson.jpg",
    status: "active",
    joinDate: new Date("2023-01-10"),
    lastAttendance: new Date("2025-04-06"), // Last Sunday
    homeAddress: "456 Oak Ave, Anytown, CA 94321",
    birthDate: new Date("1978-05-15"),
    familyId: "fam_002",
    primaryBranchId: "branch_001",
    hasCard: true,
    cardId: "card_004",
    attendanceStreak: 2,
    attendanceRate: 66,
    isChild: false,
    tags: ["worship-team", "womens-ministry"],
  },
  {
    id: "mem_006",
    firstName: "David",
    lastName: "Williams",
    email: "david.williams@example.com",
    phone: "123-456-7894",
    photoUrl: "/images/avatars/david-williams.jpg",
    status: "active",
    joinDate: new Date("2021-09-05"),
    lastAttendance: new Date("2025-03-23"), // Missed 3 weeks
    homeAddress: "789 Pine St, Anytown, CA 94321",
    birthDate: new Date("1990-02-18"),
    primaryBranchId: "branch_001",
    hasCard: true,
    cardId: "card_005",
    attendanceStreak: 0,
    attendanceRate: 55,
    isChild: false,
    tags: ["tech-team", "young-adults"],
  },
  {
    id: "mem_007",
    firstName: "Jennifer",
    lastName: "Brown",
    email: "jennifer.brown@example.com",
    phone: "123-456-7895",
    photoUrl: "/images/avatars/jennifer-brown.jpg",
    status: "active",
    joinDate: new Date("2024-02-15"),
    lastAttendance: new Date("2025-04-06"), // Last Sunday
    homeAddress: "101 Cedar Ln, Anytown, CA 94321",
    birthDate: new Date("1995-07-22"),
    familyId: "fam_003",
    primaryBranchId: "branch_002",
    hasCard: true,
    cardId: "card_006",
    attendanceStreak: 8,
    attendanceRate: 100,
    isChild: false,
    tags: ["new-member", "volunteer"],
  },
  {
    id: "mem_008",
    firstName: "Robert",
    lastName: "Jones",
    email: "robert.jones@example.com",
    phone: "123-456-7896",
    photoUrl: "/images/avatars/robert-jones.jpg",
    status: "visitor",
    lastAttendance: new Date("2025-04-06"), // Last Sunday - first visit
    primaryBranchId: "branch_001",
    hasCard: false,
    isChild: false,
    tags: ["visitor", "follow-up"],
  },
  {
    id: "mem_009",
    firstName: "William",
    lastName: "Taylor",
    email: "william.taylor@example.com",
    phone: "123-456-7897",
    photoUrl: "/images/avatars/william-taylor.jpg",
    status: "inactive",
    joinDate: new Date("2020-06-01"),
    lastAttendance: new Date("2024-12-25"), // Christmas - not attended since
    homeAddress: "222 Maple Dr, Anytown, CA 94321",
    birthDate: new Date("1970-10-05"),
    primaryBranchId: "branch_001",
    hasCard: true,
    cardId: "card_007",
    attendanceStreak: 0,
    attendanceRate: 0,
    isChild: false,
    tags: ["inactive", "former-volunteer"],
  },
  {
    id: "mem_010",
    firstName: "James",
    lastName: "Martinez",
    email: "james.martinez@example.com",
    phone: "123-456-7898",
    photoUrl: "/images/avatars/james-martinez.jpg",
    status: "active",
    joinDate: new Date("2022-11-20"),
    lastAttendance: new Date("2025-04-06"), // Last Sunday
    homeAddress: "333 Birch Blvd, Anytown, CA 94321",
    birthDate: new Date("1982-03-15"),
    familyId: "fam_004",
    primaryBranchId: "branch_002",
    hasCard: true,
    cardId: "card_008",
    attendanceStreak: 12,
    attendanceRate: 95,
    isChild: false,
    tags: ["ministry-leader", "mens-group"],
  },
];
