/**
 * Module Registry - Single Source of Truth for All Modules
 * This registry defines all available modules and their configuration
 * When a module is disabled here, it should not appear anywhere in the application
 */

export interface ModuleConfig {
  id: string;
  name: string;
  description: string;
  path: string;
  icon: string;
  category: 'Admin' | 'Core' | 'Shared';
  enabled: boolean;
  version: string;
  dependencies: string[];
  features: string[];
  permissions?: string[];
  metadata?: Record<string, any>;
}

export interface ModuleRegistry {
  modules: ModuleConfig[];
  lastUpdated: string;
  version: string;
}

// Default module registry - This will be synced with God Mode settings
export const DEFAULT_MODULES: ModuleConfig[] = [
  // Admin Modules
  {
    id: 'god-mode',
    name: 'God Mode',
    description: 'System-wide administration',
    path: '/dashboard/god-mode',
    icon: 'Shield',
    category: 'Admin',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['System config', 'User management', 'Module management'],
    permissions: ['GOD_MODE'],
  },
  {
    id: 'super-admin',
    name: 'Super Admin',
    description: 'Super administrator panel',
    path: '/dashboard/super-admin',
    icon: 'Shield',
    category: 'Admin',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Full system access'],
    permissions: ['SUPER_ADMIN'],
  },

  // Core Modules - Member Management
  {
    id: 'members',
    name: 'Members',
    description: 'Member management',
    path: '/dashboard/members',
    icon: 'Users',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Add/Edit/Delete', 'Import/Export', 'Profiles'],
  },
  {
    id: 'member',
    name: 'Member Profile',
    description: 'Individual member profile',
    path: '/dashboard/member',
    icon: 'Users',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['members'],
    features: ['View profile', 'Edit details'],
  },
  {
    id: 'families',
    name: 'Families',
    description: 'Family management',
    path: '/dashboard/families',
    icon: 'Users',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['members'],
    features: ['Family trees', 'Relationships'],
  },
  {
    id: 'groups',
    name: 'Groups',
    description: 'Group management',
    path: '/dashboard/groups',
    icon: 'Users',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['members'],
    features: ['Create groups', 'Manage members'],
  },
  {
    id: 'volunteers',
    name: 'Volunteers',
    description: 'Volunteer management',
    path: '/dashboard/volunteers',
    icon: 'Users',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['members'],
    features: ['Volunteer registry', 'Scheduling'],
  },
  {
    id: 'children',
    name: 'Children',
    description: 'Children and youth',
    path: '/dashboard/children',
    icon: 'Users',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['members'],
    features: ['Youth registry', 'Programs'],
  },
  {
    id: 'user-management',
    name: 'User Management',
    description: 'User accounts',
    path: '/dashboard/user-management',
    icon: 'Users',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['User accounts', 'Roles', 'Permissions'],
  },

  // Core Modules - Financial
  {
    id: 'finances',
    name: 'Finances',
    description: 'Financial management',
    path: '/dashboard/finances',
    icon: 'DollarSign',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['members'],
    features: ['Donations', 'Expenses', 'Reports'],
  },
  {
    id: 'branch-finances',
    name: 'Branch Finances',
    description: 'Branch financial management',
    path: '/dashboard/branch-finances',
    icon: 'DollarSign',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['finances'],
    features: ['Branch budgets', 'Local reports'],
  },
  {
    id: 'subscription-manager',
    name: 'Subscriptions',
    description: 'Subscription management',
    path: '/dashboard/subscription-manager',
    icon: 'DollarSign',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['members'],
    features: ['Plans', 'Billing', 'Payments'],
  },

  // Core Modules - Events & Activities
  {
    id: 'events',
    name: 'Events',
    description: 'Event management',
    path: '/dashboard/events',
    icon: 'Calendar',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['members'],
    features: ['Create events', 'Registration', 'Attendance'],
  },
  {
    id: 'calendar',
    name: 'Calendar',
    description: 'Calendar and scheduling',
    path: '/dashboard/calendar',
    icon: 'Calendar',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Schedule events', 'View calendar'],
  },
  {
    id: 'attendance',
    name: 'Attendance',
    description: 'Attendance tracking',
    path: '/dashboard/attendance',
    icon: 'CheckCircle',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['members'],
    features: ['Check-in', 'Reports', 'Analytics'],
  },
  {
    id: 'pastoral-care',
    name: 'Pastoral Care',
    description: 'Pastoral care management',
    path: '/dashboard/pastoral-care',
    icon: 'Heart',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['members'],
    features: ['Care tracking', 'Follow-ups'],
  },
  {
    id: 'prayer-requests',
    name: 'Prayer Requests',
    description: 'Prayer request management',
    path: '/dashboard/prayer-requests',
    icon: 'Heart',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['members'],
    features: ['Submit requests', 'Track prayers'],
  },

  // Core Modules - Communication
  {
    id: 'communication',
    name: 'Communication',
    description: 'Multi-channel messaging',
    path: '/dashboard/communication',
    icon: 'MessageSquare',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['members'],
    features: ['Email', 'SMS', 'Push notifications'],
  },
  {
    id: 'broadcasts',
    name: 'Broadcasts',
    description: 'Broadcasting system',
    path: '/dashboard/broadcasts',
    icon: 'MessageSquare',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['communication'],
    features: ['Mass messages', 'Scheduling'],
  },
  {
    id: 'notifications',
    name: 'Notifications',
    description: 'Notification management',
    path: '/dashboard/notifications',
    icon: 'MessageSquare',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Push alerts', 'Preferences'],
  },
  {
    id: 'sermons',
    name: 'Sermons',
    description: 'Sermon management',
    path: '/dashboard/sermons',
    icon: 'MessageSquare',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Upload sermons', 'Archive', 'Share'],
  },

  // Core Modules - Sacraments & Registries
  {
    id: 'sacraments',
    name: 'Sacraments',
    description: 'Sacrament management',
    path: '/dashboard/sacraments',
    icon: 'CheckCircle',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['members'],
    features: ['Record sacraments', 'Certificates'],
  },
  {
    id: 'birth-registry',
    name: 'Birth Registry',
    description: 'Birth registration',
    path: '/dashboard/birth-registry',
    icon: 'CheckCircle',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Birth records', 'Certificates'],
  },
  {
    id: 'death-register',
    name: 'Death Register',
    description: 'Death registration',
    path: '/dashboard/death-register',
    icon: 'CheckCircle',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Death records', 'Certificates'],
  },

  // Core Modules - Organization & Admin
  {
    id: 'admin',
    name: 'Admin',
    description: 'System administration',
    path: '/dashboard/admin',
    icon: 'Settings',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['System config', 'User roles'],
  },
  {
    id: 'branches',
    name: 'Branches',
    description: 'Multi-branch management',
    path: '/dashboard/branches',
    icon: 'Shield',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Branch setup', 'Hierarchy'],
  },
  {
    id: 'branch',
    name: 'Branch',
    description: 'Branch operations',
    path: '/dashboard/branch',
    icon: 'Shield',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['branches'],
    features: ['Branch settings', 'Operations'],
  },
  {
    id: 'branch-admin',
    name: 'Branch Admin',
    description: 'Branch administration',
    path: '/dashboard/branch-admin',
    icon: 'Shield',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: ['branches'],
    features: ['Branch control'],
  },
  {
    id: 'zones',
    name: 'Zones',
    description: 'Zone management',
    path: '/dashboard/zones',
    icon: 'MapPin',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Create zones', 'Manage areas'],
  },
  {
    id: 'ministries',
    name: 'Ministries',
    description: 'Ministry management',
    path: '/dashboard/ministries',
    icon: 'Sparkles',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Ministry setup', 'Teams'],
  },

  // Core Modules - Reporting & Analytics
  {
    id: 'analytics',
    name: 'Analytics',
    description: 'Analytics and dashboards',
    path: '/dashboard/analytics',
    icon: 'BarChart3',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Dashboards', 'Charts', 'Insights'],
  },
  {
    id: 'reports',
    name: 'Reports',
    description: 'Report generation',
    path: '/dashboard/reports',
    icon: 'BarChart3',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Generate reports', 'Export data'],
  },
  {
    id: 'report-builder',
    name: 'Report Builder',
    description: 'Custom report builder',
    path: '/dashboard/report-builder',
    icon: 'BarChart3',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Custom reports', 'Templates'],
  },
  {
    id: 'audits',
    name: 'Audits',
    description: 'Audit logging',
    path: '/dashboard/audits',
    icon: 'Lock',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Audit trails', 'Compliance'],
  },

  // Core Modules - Content & Integration
  {
    id: 'cms',
    name: 'CMS',
    description: 'Content management',
    path: '/dashboard/cms',
    icon: 'Edit2',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Content pages', 'Media', 'Publishing'],
  },
  {
    id: 'website-integration',
    name: 'Website Integration',
    description: 'Website integration',
    path: '/dashboard/website-integration',
    icon: 'Edit2',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Website sync', 'API integration'],
  },
  {
    id: 'mobile-integration',
    name: 'Mobile Integration',
    description: 'Mobile app integration',
    path: '/dashboard/mobile-integration',
    icon: 'Edit2',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Mobile sync', 'Push notifications'],
  },
  {
    id: 'workflows',
    name: 'Workflows',
    description: 'Workflow automation',
    path: '/dashboard/workflows',
    icon: 'Zap',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Automation', 'Triggers', 'Actions'],
  },

  // Core Modules - Assets & Settings
  {
    id: 'assets',
    name: 'Assets',
    description: 'Asset management',
    path: '/dashboard/assets',
    icon: 'HardDrive',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Asset registry', 'Tracking'],
  },
  {
    id: 'settings',
    name: 'Settings',
    description: 'System settings',
    path: '/dashboard/settings',
    icon: 'Settings',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Configuration', 'Preferences'],
  },
  {
    id: 'profile',
    name: 'Profile',
    description: 'User profile management',
    path: '/dashboard/profile',
    icon: 'Users',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['User profiles', 'Settings'],
  },

  // Shared Components
  {
    id: 'components',
    name: 'Components',
    description: 'UI components library',
    path: '/dashboard/components',
    icon: 'Sparkles',
    category: 'Shared',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['UI components', 'Design system'],
  },

  // Worship
  {
    id: 'worship',
    name: 'Worship',
    description: 'Worship management',
    path: '/dashboard/worship',
    icon: 'Heart',
    category: 'Core',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    features: ['Worship planning', 'Teams'],
  },
];
